### ISSUE TITLE
Drawing Polyline tool crosses International Date Line

### ISSUE THREAD

**Issue by gmarshall56** [geoman-io/leaflet-geoman#1018]
Using the Draw Polyine tool I drew a line from California, USA, to Hawaii.  I then drew another line from Hawaii to China.  Geoman then created another line that wrapped around the world.  This line is not wanted.  Is this a type of "auto complete" feature?  How do I tell Geoman to not do this?  Thank you for your time
![GeomanDrawAcrossDateline](https://user-images.githubusercontent.com/5943189/139074070-38ad6954-475b-4f60-bd25-676422290e7c.JPG)
s?

**Comment by Falke-Design** [comment]
The problem is that turf wraps the coords to the default one. This means if you put in a lat coordinate into turf which is lower/greater then -180/180 it will add 360 to it, to wrap it to the "normal" coords.

Possible code to fix:
I check if one coord is lower then -180, if yes store it in a Flag. Then loop through all buffer coords and subtract 360 from it, to move it to the next "world copy".
```
const isAfter180 = e.layer.getLatLngs().flat(2)[0].lng < -180 || e.layer.getLatLngs().flat(2)[1].lng < -180;
                        
            const buffered = turf.buffer(e.layer.toGeoJSON(), 50, {
              units: "miles"
            });
            
            if(isAfter180){
              var coords = [];
              buffered.geometry.coordinates[0].forEach((coord)=>{
                if(coord[0] > 0){
                  coord[0] = coord[0] - (180*2);
                }
                coords.push(coord);
              })
              buffered.geometry.coordinates[0] = coords;
            }
            
            const bufferedLayer = L.geoJSON(buffered, {
              style: bufferStyle
            });
```
But this will only work for your custom sample and not in general. (What if more then 2 points, I have not checked if `coords[0] > 0` makes always sense, ...)
