### ISSUE TITLE
Get coordinates of drawn layer as it is being drawn

### ISSUE THREAD

**Issue by rumski20** [geoman-io/leaflet-geoman#1072]
Hello, I am looking for a way to highlight features in a geojson layer as I draw a rectangle over them (using the bounds of the draw layer as it is updated). Is there a way to do this?  
I thought [this discussion](https://github.com/geoman-io/leaflet-geoman/discussions/843) might be close to what I need, but I couldn't find a way to pass an existing _empty_ layer to `.enableDraw()` so that the `pm:snapdrag` function would be activated.

Do you have any suggestions? Thanks.

**Comment by Falke-Design** [comment]
I think you need to listen on the `pm:create` event:
```
map.on('pm:create', (e) => {
  if(e.layer instanceof L.Marker){
     console.log(e.layer.getLatLngs();
  }
});
```
or for while drawing the `pm:drawstart` event and then the `workingLayer`
```
map.on('pm:drawstart', (e) => {
  console.log(e);
});
```

**Comment by rumski20** [comment]
Thanks for the response.
I tried using the code that you posted in the discussion I referenced:
```
      map.on('pm:drawstart', ({ workingLayer }) => {
        console.log('workingLayer: ', workingLayer)
        workingLayer.on('pm:snapdrag', e => {
          console.log(e)
        })
```
`workingLayer` shows up in the console. But I never see anything from the `snapdrag` event. Is that because I am trying to draw a rectangle? If so, do you have an event for listening to a layer while drawing?

**Comment by Falke-Design** [comment]
`snapdrag` is not fired because there are no other layers on the map, on which it can snapped. But go away from this event, it is not the correct one for your usage.

You want to draw a rectangle and get the layers below.

If you want to get the layers **AFTER** drawing, use this:
```
map.on('pm:create', (e) => {
  if(e.layer instanceof L.Rectangle){
     var bounds = e.layer.getBounds();
     YOUR_FUNCTION_TO_GET_THE_LAYERS_IN_BOUNDS(bounds);
  }
})
```

if you want to get the layers below the rectangle **WHILE** drawing, use this:
```
function getBoundsOfLayer (e){
  console.log(this.getBounds()); // this == layer, because while adding the move-event-listener with on, we pass the layer as context
   YOUR_FUNCTION_TO_GET_THE_LAYERS_IN_BOUNDS(this.getBounds());
};

map.on('pm:drawstart', (e) => {
  var layer = e.workingLayer;
  if(layer instanceof L.Rectangle){
    map.pm.Draw.Rectangle._hintMarker.on('move', getBoundsOfLayer, layer);
  }
});
```

**Comment by rumski20** [comment]
Thank you. This was helpful and allowed me to achieve what I wanted.
I needed to have a way to check if the first point of the rectangle had been placed so I did something like this:
```
          if (
            window.L.DomUtil.hasClass(
              this.themap.pm.Draw.Rectangle._startMarker._icon,
              'visible'
            )
          ) {
            ....continue with code
            }
```
I'm not sure if there is a better way to do so, but this worked for me.
Thank you again for your help, and for this awesome library.

**Comment by moshulu** [comment]
I'm glad this was resolved, but I think this thread raised more questions than it answered. 

Currently, my way of detecting events while drawing is to do:
```
map.on('pm:drawstart', (e) => {
var workingLayer = e.workingLayer

workingLayer.on('pm:snapdrag', (e) => {
   // do something while drawing, and only while drawing

} // end snapdrag

} // end drawstart

```

As @Falke-Design correctly pointed out, there `pm:snapdrag` only gets fired when there's a layer **to get snapped to** already on the map. This poses errors when you want something to happen while drawing when there's nothing on the map currently. I suspect an ugly workaround would be to create a shape on the map at the beginning of drawing, out-of-view from the user (north or south pole?) so that `pm:snapdrag` would be called. Regardless of this workaround, I believe there should be an event that is fired while drawing a `Circle`, `Polygon`, or `Rectangle`.
