### ISSUE TITLE
L.PM is undefined when packaged with webpack

### ISSUE THREAD

**Issue by tfrancart** [geoman-io/leaflet-geoman#1476]
Hello and sorry if this is an obvious question, or answered somewhere.

I am building a Typescript app integrating geoman + leaflet. The app works fine on dev page (`npm run start`), but when packaged with webpack I get this error:

```
Uncaught TypeError: L.PM is undefined
    addInitHooks leaflet-geoman.min.js:1
    callInitHooks leaflet-src.js:359
    initialize leaflet-src.js:3269
    n leaflet-src.js:302
    map leaflet-src.js:4863
    Ae MapWidget.ts:179
    render AddUserInputBtn.ts:21
```

I suspect this is due to the import or packaging of the app.

Here are the imports in my Typescript file:

```typescript
// L needs to be imported *before* leaflet-geoman-free
import L, { LatLng, Rectangle, PolylineOptions, Polygon } from "leaflet";
// ... snip
import "leaflet/dist/leaflet.css";
import "@geoman-io/leaflet-geoman-free";
import "@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.css";
// ... snip
```

Here are my dependencies:

```json
  "devDependencies": {
    "@types/leaflet": "^1.7.10",
    "@types/leaflet-draw": "^1.0.5",
  },
  "dependencies": {
    "@geoman-io/leaflet-geoman-free": "^2.13.0",
    "leaflet": "^1.8.0",
    "n3": "^1.3.5",
  }
```

I found that if I move the import line from leaflet *after* the import line from geoman I get another error `L is undefined`.
Could this be a namespace conflict with the `"leaflet"` import ? because I see that geoman redefines it own "leaflet" namespace. Could it be that webpack picks up the wrong one ?

Anything else I am missing ? 
Thanks !

**Comment by Falke-Design** [comment]
I can't help you much but for me it looks like that after bundleing with webpack, the automatically initialization of Geoman on the global variable `L` didn't work correctly. This can be because your code runs a different `leaflet-geoman` instance or because some other plugin maybe overwrites the `L` variable.

Try the following, maybe one of them works:

- Try to run after initialization `window.L = L.noConflict();` (https://leafletjs.com/reference.html#noconflict)
- Remove other plugins until Geoman works again

**Comment by tfrancart** [comment]
Thanks, your remark led me progressively to the solution : Another component of mine integrated in the page is *also* importing leaflet. Somehow this causes a confusion for geoman. I need to also import geoman in the other plugin for it to work in the first plugin...
