### ISSUE TITLE
How drag mode works with markers?

### ISSUE THREAD

**Issue by NtsDK** [geoman-io/leaflet-geoman#512]
Hi!

I need to listen dragend event on marker. In my expectations I initialized it right but it doesn't work.
I found similar problem here https://github.com/geoman-io/leaflet-geoman/issues/190
And conclusion was listen to pm:edit event.

How drag events should work? Is dragging marker a use case for drag events?

Demo: https://jsfiddle.net/dvh1r2je/

**Comment by rcollette** [comment]
Oddly enough, if you enable a layer with draggable, you do get the drag events.

https://jsfiddle.net/cmbopjae/

```JavaScript
    const marker = L.circleMarker([39.74739, -105]).addTo(map);
    
    marker.on('pm:edit', () => console.log('pm:edit'));
    marker.on('pm:drag', () => console.log('pm:drag'));
    marker.on('pm:dragstart', () => console.log('pm:dragstart'));
    marker.on('pm:dragend', () => console.log('pm:dragend'));
    marker.pm.enable({draggable:true});
```

I was looking at this because I am in some sort of other pickle where my draggable circle marker, basically created the same way as this, doesn't drag but rather the entire map pans instead.  Only thing I can think of is that I am removing a layer from the map prior to this, and there seems to be some known issues with that.

**Comment by AdamJamesNaylor** [comment]
I'm seeing the same issue, I can't seem to bind to any of the drag events for markers.

**Comment by codeofsumit** [comment]
hmm seems like a bug. Thanks for reporting I will take a closer look!

**Comment by hoangeiu** [comment]
Has this problem been fixed?

**Comment by codeofsumit** [comment]
Fixed by #591 

Will be in the next release @hoangeiu

**Comment by cswww** [comment]
Is it solved now? I tried or couldn't

**Comment by Falke-Design** [comment]
Yes this is solved look into: https://jsfiddle.net/dvh1r2je/
