### ISSUE TITLE
Adding marker in Circle with popups

### ISSUE THREAD

**Issue by cheazo** [geoman-io/leaflet-geoman#543]
Hey there, i'll try to add an marker onto an circle-layer which has an popup in it. But i can't.

Allways when i'll do a 'click' onto the circle to place the marker, then the popup comes up.
This happens in all differend shapes when i'll try to set a marker on them. But not when i'll try to draw an circle in an circle or in another shape. Only with markers.

Could you please check this out or tell me how to handle that?

Thx

**Comment by codeofsumit** [comment]
@cheazo I'm unaware of your popup code, please create a JSfiddle showing the problem and I'm happy to help you out

**Comment by Falke-Design** [comment]
Leaflet opens a popup if the clicked layer have one. [Leaflet src](https://github.com/Leaflet/Leaflet/blob/41706c01685320e3fd1d93d19e59b3275d3a90cb/src/layer/Popup.js#L390)

![markerpopup](https://s6.gifyu.com/images/marker_popup.gif)

It is working for other layer types, because they are having the hint markers and while clicking, the hint marker click event is triggered and not the event of the layer below. But if the hint marker is snapped, it is also not working.

Current state: https://jsfiddle.net/falkedesign/yu0925cf/
Fix one: Overwrite _openPopup from leaflet: https://jsfiddle.net/falkedesign/2opa4rwy/
Fix two: fixes only the marker problem, change iconAnchor: https://jsfiddle.net/falkedesign/Lypkgqo5/

Also I thinking of, if it is possible to have always a vanished marker or layer below the cursor and catching the click event.

**Comment by codeofsumit** [comment]
@Falke-Design I think another invisible marker always attached to the mouse would be the cleanest solution. That would probably also be the base to fix multiple other problems 🤔

**Comment by Falke-Design** [comment]
@codeofsumit a easier fix would be to use the event `mousedown`, it is triggered on the map, also when a popup is binded to a layer. What problems can happen if we change from `click` to `mousedown`?
