### ISSUE TITLE
MultiPoint pm:edit not trigger

### ISSUE THREAD

**Issue by shym88** [geoman-io/leaflet-geoman#549]
pm:edit was not triggered when data type is Multipoint. Can you have any suggestion?
```
   const theCollection = L.geoJson(datajson, {
      onEachFeature: function (feature, layer) {
          layer.bindPopup('<p>'+feature.properties.name+'</p>');
      }
    });
 theCollection.addTo(map);
    map.pm.addControls({
      position: 'topleft',
      drawMarker: true,
      drawCircle: false,
      drawPolygon: true,
      drawPolyline: false,
      drawCircleMarker:false,
      drawRectangle:false,
    });
    theCollection.on('pm:edit', function(e) {
      console.log("pm:edit");
    });
```

**Comment by codeofsumit** [comment]
Can you share the datajson so I ca try and reproduce this?

**Comment by shym88** [comment]
`{"type":"FeatureCollection","features":[{"type":"Feature","id":"deneme.1","geometry":{"type":"MultiPoint","coordinates":[[32.83604819,40.0169319]]},"geometry_name":"geom","properties":{"id":1,"name":"ABC"}},{"type":"Feature","id":"deneme.2","geometry":{"type":"MultiPoint","coordinates":[[32.8298979,40.02567418]]},"geometry_name":"geom","properties":{"id":2,"name":"XYZ"}}],"totalFeatures":2,"numberMatched":2,"numberReturned":2,"timeStamp":"2020-03-19T06:47:23.277Z","crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::4326"}}}`

Also pm:edit not triggeted when datatype is Multipoligon

**Comment by Falke-Design** [comment]
The Problem is, that the layergroup `theCollection` has also layergroups as children. The marker fires the event `pm:edit` then the layergroup (lg1) which contains the marker, also fire the `pm:edit` event. But the layergroup `theCollection` which contains lg1 not fire `pm:edit`.

This can be fixed when the filter `instanceof L.LayerGroup` is removed.
https://github.com/geoman-io/leaflet-geoman/blob/9f3cecdc0b5cbd029bf5ea1916ea26f188bcda5e/src/js/Edit/L.PM.Edit.LayerGroup.js#L48

I don't know why layergroups are excluded so I didn't created a PR. (But all cypress tests were successful)

**Comment by codeofsumit** [comment]
Hm I think I excluded it to not cause any infinite loops 🤔
But as I did not properly commented it (or tested it) it seems to be very old and I'm willing to test it to remove it.
Feel free to open a PR 👌
