### ISSUE TITLE
Draw Multipolygon

### ISSUE THREAD

**Issue by nicokant** [geoman-io/leaflet-geoman#550]
Hi, 
thanks for your work!
Is it possible to add multipolygon support for drawing?

**Comment by codeofsumit** [comment]
Hi, @nicokant.
You can't really "draw multipolygons" because MultiPolygons are GeoJSON format while leaflet just has layers but my guess is you want grouped polygons. So for example you draw 2 polygons and they are automatically added to a LayerGroup in Leaflet.

Is that what you want? How could that look like in the UI?
The more I think about it, the more I arrive at the conclusion that this should be part of your application logic. For example, you can listen to the `pm:create` event and add the layers you want to specific LayerGroups or add their GeoJSON representation to a MultiPolygon of your choice.

Closing the issue for now but let's discuss this further in case I misunderstood you 👍
