### ISSUE TITLE
Image TileGroup instead of Map

### ISSUE THREAD

**Issue by moulikrishna** [geoman-io/leaflet-geoman#704]
Hi,

Image TileGroup instead of Map Tiles, is this feature available, if yes please let me know

Thanks

**Comment by Falke-Design** [comment]
Can you please explain a litte bit more. 
What have tiles to do with geoman? We don't support drawing / editing map tiles. Or what do you mean with instead of Map tiles?
Also I don't know what Image TileGroup is, can you plese explain it and a example would be nice how Image TileGroups are working.

Let us see if I can help 😉

**Comment by Falke-Design** [comment]
I close this because I have no idea what the OP means and there is no response
