### ISSUE TITLE
Issue with Drawing Markers in geoman 2.8.0 - All layers are enabled on pm:create

### ISSUE THREAD

**Issue by henrikmaa** [geoman-io/leaflet-geoman#719]
After updating to Geoman 2.8.0 I have an issue that if i create a marker all other layers goes into editing mode. I cant reproduce this in a fiddle. 

What im doing exactly: 
 ```
map.pm.enableDraw('Marker', {
      snappable: true,
      snapDistance: 20,
      finishOn: 'click' || 'mousedown',
      continueDrawing: false <-- using this new addition of 2.8.0 (does not make a difference to my issue if i have it to true)
    });
```
Then on `pm:create` All layers are enabled for some reason

I think this may be an issue of rendering by using React, but I tried to remove all `pm.enable()` from my code, so basically it is just enabling by itself for no reason. I suspect there is maybe an issue in #696? Altough I am not using globalEditMode at all

If I was smart enough to understand properly whats happening  I would definitely give a better explanation...
Maybe it is not an issue with geoman at all, buy maybe you guys know what addition of 2.8.0 which may break this?

If I use geoman 2.7.0 it works fine.

Edit: Also tested with CircleMarker, which also makes all layers go into editing mode. If I create a Polyline or Polygon it works normal.

**Comment by henrikmaa** [comment]
The problem was indeed a project code issue.

If anyone has something similar in the future:

I added the layer to LayerGroup on pm:create - `features.addLayer(e.layer)` not sure why it enables all layers tho.

**Comment by Falke-Design** [comment]
I reopen this issue because it is a "bug" of the layergroup handling.

You can fix this when you disable the edit mode for markers they are drawn: `map.pm.setGlobalOptions({markerEditable: false})`


The problem is that by adding a layer to the layergroup, geoman is looking if a layer in the group is enabled (marker after placing) and if so all other layers will be also enabled. 
https://github.com/geoman-io/leaflet-geoman/blob/ff58d546ae5807a331485c16b5ac442b6bbce527/src/js/Edit/L.PM.Edit.LayerGroup.js#L31-L33

**Comment by geohuz** [comment]
I'm encountering this issue today, wondering how can I get the lastest fix or have to wait the next version?

**Comment by henrikmaa** [comment]
@geohuz fork geoman and use this commit until geoman has a new release :)

**Comment by Falke-Design** [comment]
New Release is out
