### ISSUE TITLE
Drag show error sometimes 

### ISSUE THREAD

**Issue by arshdoda** [geoman-io/leaflet-geoman#776]
Hi,
I have loaded around 1000 features. When I drag a certain feature slowly, it works fine and if I drag a feature fast, error shows :: "TypeError: Cannot read property 'dragging' of null".

I have attached a video for the reference

[https://antef-test-bucket.s3.ap-south-1.amazonaws.com/deepin-screen-recorder_Select+area_20210123180447.mp4](url)

**Comment by Falke-Design** [comment]
Would it possible to create a demo?

Which versionf leaflet and geoman are you using? I can't reproduce


It looks like that it throws an error because the layer has no _map attribute anymore ... Maybe because while the fast drag you release the mouse outside of the dragged layer. But when I tried this I was not able to be fast enough to release the mouse before the layer moved.

https://github.com/geoman-io/leaflet-geoman/blob/7cdb0edadc800edf3498fe6f78d140bccaa0aaa9/src/js/Mixins/Dragging.js#L122-L129

**Comment by Falke-Design** [comment]
Closeing this issue because this issue happend with Version `2.3.0` and we are know at `2.11.2` with some updates in Dragging.
