### ISSUE TITLE
How to enable edit mode on specific layer if pmIgnore is false

### ISSUE THREAD

**Issue by AndrejGajdos** [geoman-io/leaflet-geoman#806]
Hi, thanks for this amazing plugin. I have a use case, which I am not able to get working. I have a map with a lot of geojson objects and by default, they are not editable. I render them with option `pmIgnore={true}`. When user clicks on geojson, I would like to enable edit mode only on clicked geojson.

I tried to apply this code to geojson layer, because I found it in a previous issue, but its not working.

```
leafletLayer.pm = new L.PM.Edit.Rectangle(leafletLayer);
leafletLayer.pm.enable();
```

and

```
L.PM.reInitLayer(leafletLayer);
leafletLayer.pm.enable();
```

Here is a [codesandbox.io](https://codesandbox.io/s/peaceful-snyder-kyc3h?file=/src/useDraw.js). Thanks for any help.

**Comment by Falke-Design** [comment]
The problem is that `leafletLayer` is a Polygon and not a Rectangle. When you change `leafletLayer.pm = new L.PM.Edit.Rectangle(leafletLayer);` to `leafletLayer.pm = new L.PM.Edit.Polygon(leafletLayer);` i works. But I think you want to use it as a Rectangle, then you have to create the layer instead as Polygon as a Rectangle.

You can change this in the `onEachFeature` function of `L.GeoJSON` or you create a new instance of the layer in the loop:

``` 
leafletLayer.removeFrom(mapRef);
leafletLayer = L.rectangle(leafletLayer.getBounds()).addTo(mapRef);
leafletLayer.pm = new L.PM.Edit.Rectangle(leafletLayer);
```

**Comment by AndrejGajdos** [comment]
@Falke-Design thank you!
