### ISSUE TITLE
reInitLayer does not accept geojson layer

### ISSUE THREAD

**Issue by tirli** [geoman-io/leaflet-geoman#873]
I tried to create a GeoJSON layer and it was immediately grabbed by geoman allowing me to edit shapes. Though I don't need it to be editable all the time. So I added the `pmIgnore` option to the geojson layer. Then I tried to use these lines from [docs](https://github.com/geoman-io/leaflet-geoman#init-leaflet-geoman)
```
layer.options.pmIgnore = false;
L.PM.reInitLayer(layer);
```

Though seems like [reInitLayer](https://github.com/geoman-io/leaflet-geoman/blob/e1f5e542345a98b7b2bd2b775b105bde0e235ca8/src/js/L.PM.js#L184) doesn't accept geojson layer. 

Actual: nothing happened if you use geojson layer
Expected: ​geojson layer becomes editable

[Reproduction example](https://jsfiddle.net/mjv2efp0/)

**Comment by Falke-Design** [comment]
You are right, a LayerGroup ( GeoJSON too) not working to reinit the layers, it's a bug. Currently it loops through all layers in the LayerGroup and reinit each layer instead of the whole group.
So if you call `layer.options.pmIgnore=false` the property is only on the GeoJSON-layer changed. If you use `setStyle()` the option `pmIgnore` is passed to all childs of the group too and it works.

Workaround for the layer childs:
```
layer.setStyle({pmIgnore: false});
L.PM.reInitLayer(layer);  
```

If you need Geoman working on the GeoJSON-Layer you can call:
```
layer.pm = new L.PM.Edit.LayerGroup(layer);
```
