### ISSUE TITLE
enableGlobalCutMode could't work

### ISSUE THREAD

**Issue by Dzxwind** [geoman-io/leaflet-geoman#880]
Hello! I like the geoman library very much.
When I was doing my own demo, I found that the "draw" method in asynchrony could not trigger the "cut".
Here is the demo
https://jsfiddle.net/4okvL2qb/
1. Wait for enableDraw('Polygon') in setTimeout
2. draw a polygon
3. draw another polygon and cut the first polygon
4. the first polygon can't be cut

Wait for your reply!

**Comment by Falke-Design** [comment]
Your code:
```
map.pm.enableDraw('Polygon', {
  continueDrawing: true
})
setTimeout(() => {
  map.pm.enableDraw('Polygon')
}, 5000);
map.on('pm:create', e => {
  map.pm.enableGlobalCutMode({
    continueDrawing: true
  })
})
```

There is a problem with enabling the cut mode in `pm:create`. You enable Poylgon drawing with `continueDrawing: true` this means that it automaticly re-enable for drawing. **BUT** you also want to enable the cut mode. Now we need to know in which order the functions are executed:
   -  enable poylgon drawing
   - create polygon -> fire `pm:create`
   - enable cut mode
   - because of `continueDrawing: true` cut mode is disabled because polygon drawing is enabled again
So this means to us, that the cut mode is not enabled and you draw a polygon again

You need to remove the cut mode function in `pm:create` or remove `continueDrawing: true`

**Comment by Dzxwind** [comment]
@Falke-Design 
Thanks for your reply.
I probably understand what you mean. Here is my real application scenario.
https://jsfiddle.net/yazuL9c0/

1. click "draw multipolygon" button
2. click "draw hole polygon"

I just want to be able to switch the “add” mode and "cut" mode when I click these two buttons. At same time, these two mode need continueDrawing: true .
I try to use map.off('pm:create'), but it doesn't work.

So what other solutions can solve this problem?

Wait for your reply!
Thanks!

**Comment by Falke-Design** [comment]
Try to add `continueDrawing: false` to the hole polygon:
```
map.pm.enableDraw('Polygon',{
        continueDrawing: false
      })
```

This is needed because the options are saved, so when you call multipolygon with `continueDrawing: true` and call `map.pm.enableDraw('Polygon')` it has `continueDrawing: true` too.

**Comment by Dzxwind** [comment]
Thanks a lot.
Problem has been resolved.
But I personally recommend that this problem be noted in the API.
Thanks to the geoman team for providing us with such a great plugin. 
Keep going!

**Comment by Falke-Design** [comment]
Nice to hear!

We already have it documented:
> The options will persist, even when the mode is enabled/disabled via the toolbar.

But maybe not on the perfect place
